### ISSUE TITLE
Error generating html files for LL reaction networks

### ISSUE THREAD

**Issue by Bernardo-lab** [dgarayr/amk-rxreader#4] opened 2024-05-23 15:02 UTC
Hi, I'm a very passionate user of automekin and amk_tools, unfortunately after reinstalling both of them I can no longer generate the html files for the low level (LL) reaction network. 
The installation gave no problems and the dependencies are all correct.
I get this error:

$ amk_gen_view.py FINAL_LL_XB RXNet -o test.html

Traceback (most recent call last):
  File "/home/bernardo/Downloads/amk_tools-master/scripts/amk_gen_view.py", line 5, in <module>
    arxviz.gen_view_cmd(args)
  File "/home/bernardo/Downloads/amk_tools-master/RXVisualizer.py", line 959, in gen_view_cmd
    data = arx.RX_parser(finaldir=args.finaldir,rxnfile=args.rxnfile,check_connection=True)
  File "/home/bernardo/Downloads/amk_tools-master/RXReader.py", line 213, in RX_parser
    leftside,rightside = [item.strip("<>-").split() for item in line]
ValueError: not enough values to unpack (expected 2, got 1)

Could you help me solve this problem please?

Thank you.

**Comment by dgarayr** [comment] 2024-05-23 15:47
Hi,
A couple of questions:
- Does this happen with multiple LL networks, or only for certain examples? 
- Is the program working for the HL network?

The issue seems to be with parsing the RXNet file: should not be too difficult to handle, but as I cannot reproduce the problem with the files I have on hand I would need to take a look at the files of the specific example that is failing. Ideally the full FINAL_LL_XB directory would be ideal, but if you cannot share it for any reason the RXNet file might be enough to diagnose the issue.

Thanks for the interest!

**Comment by Bernardo-lab** [comment] 2024-05-23 19:52
Hi,

Thank you very much for the quick response.


   - Does this happen with multiple LL networks, or only for certain
   examples?

It happens with all the LL networks that I tested, so 3, I get the same
error.


   - Is the program working for the HL network?

Yes, it works perfectly.

No problem at all, I can share with you the FINAL_LL_XB directory, attached
you can find it.

Thanks again!

 FINAL_LL_XB.zip
<https://drive.google.com/file/d/1LNY92XKWZKffOguFiyrPc-PZaX5cggdV/view?usp=drive_web>


Il giorno gio 23 mag 2024 alle ore 16:47 Diego Garay-Ruiz <
***@***.***> ha scritto:

**Comment by dgarayr** [comment] 2024-05-24 09:57
Hi,
seems to be fixed in the last commit (7572e5f). There was a change in the format of the RXNet file for the LL network that was breaking the parser. Now the latest version of the code detects this new format and processes it accordingly. 

If you can test it in both your LL and HL examples and confirm that everything works, it would be great.

**Comment by Bernardo-lab** [comment] 2024-05-24 14:10
Hi,

Thank you very much.
I tested it for both LL and HL, everything works fine.

Thanks again.



Il giorno ven 24 mag 2024 alle ore 10:57 Diego Garay-Ruiz <
***@***.***> ha scritto:

**Closed as completed** 2024-05-24 14:34 UTC
